*//--------------------------------------------------------------------------------------------------
*// $Workfile: global.inc $ $Revision: 4 $ $Date: 3/10/05 11:46a $ 
*//----------- -------------------------------------------------------------------- -----------------
               &ALPHABET      POS(0)  LEN(1) . nul    ;*// null character
               &ALPHABET      POS(8)  LEN(1) . bs     ;*// backspace
               &ALPHABET      POS(9)  LEN(1) . ht     ;*// horizontal tab
               &ALPHABET      POS(9)  LEN(1) . tab    ;*// tab
               &ALPHABET      POS(10) LEN(1) . nl     ;*// new line
               &ALPHABET      POS(10) LEN(1) . lf     ;*// line feed
               &ALPHABET      POS(11) LEN(1) . vt     ;*// vertical tab
               &ALPHABET      POS(12) LEN(1) . ff     ;*// form feed
               &ALPHABET      POS(13) LEN(1) . cr     ;*// carriage return
               &ALPHABET      POS(47) LEN(1) . fSlash ;*// forward slash
               &ALPHABET      POS(92) LEN(1) . bSlash ;*// back slash

               TRUE           =   1
               FALSE          =   0
               digits         =  '0123456789'

